---
author: "https://github.com/jspaaks"
branding:
  color: purple
  icon: check
description: "Validate CITATION.cff files, and convert to other citation formats."
name: cffconvert
runs:
  entrypoint: cffconvert
  args:
    - --validate
  image: docker://citationcff/cffconvert:2.0.0
  using: docker
